sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: cqx
    password: tinashe333
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tHLGZikYwQR9X8niBJi
    access-key-secret: UvcyxNkJIU82ItLUmX3aiQGL68lVYF
    bucket-name: sky-take-ki
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1
  wechat:
      appid: wx79e3c0d1a37c6fb5
      secret: 89ec97e0d6212aec78260faffec61774